# Generated by Django 4.2.30 on 2026-09-27 23:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_chat', models.ForeignKey(blank=True, db_column='id_chat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('id_articulo', models.ForeignKey(db_column='id_articulo', on_delete=django.db.models.deletion.CASCADE, to='core.articulo')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_chat', models.ForeignKey(db_column='id_chat', on_delete=django.db.models.deletion.CASCADE, to='core.chat')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='id_articulo',
            field=models.ForeignKey(db_column='id_articulo', on_delete=django.db.models.deletion.CASCADE, to='core.articulo'),
        ),
        migrations.AddField(
            model_name='chat',
            name='id_comprador',
            field=models.ForeignKey(db_column='id_comprador', on_delete=django.db.models.deletion.RESTRICT, related_name='chats_como_comprador', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='chat',
            name='id_vendedor',
            field=models.ForeignKey(db_column='id_vendedor', on_delete=django.db.models.deletion.RESTRICT, related_name='chats_como_vendedor', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id_valoracion', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_emisor', models.ForeignKey(db_column='id_emisor', on_delete=django.db.models.deletion.RESTRICT, related_name='valoraciones_emitidas', to='core.usuario')),
                ('id_receptor', models.ForeignKey(db_column='id_receptor', on_delete=django.db.models.deletion.RESTRICT, related_name='valoraciones_recibidas', to='core.usuario')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
            options={
                'unique_together': {('id_venta', 'id_emisor')},
            },
        ),
        migrations.CreateModel(
            name='Foto_Articulo',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.CharField(max_length=255)),
                ('es_principal', models.BooleanField(default=False)),
                ('id_articulo', models.ForeignKey(db_column='id_articulo', on_delete=django.db.models.deletion.CASCADE, to='core.articulo')),
            ],
            options={
                'unique_together': {('id_articulo', 'id_foto')},
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_articulo', models.ForeignKey(db_column='id_articulo', on_delete=django.db.models.deletion.CASCADE, to='core.articulo')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'unique_together': {('id_usuario', 'id_articulo')},
            },
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_acordada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
            options={
                'unique_together': {('id_venta', 'id_detalle')},
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('id_articulo', models.ForeignKey(db_column='id_articulo', on_delete=django.db.models.deletion.CASCADE, to='core.articulo')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'unique_together': {('id_usuario', 'id_articulo')},
            },
        ),
    ]
