# Generated by Django 4.2.30 on 2026-09-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chat_alter_articulo_precio_alter_articulo_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='estado_publicacion',
            field=models.CharField(default='Disponible', max_length=20),
        ),
    ]
